### ISSUE TITLE
Latest Jquery 3.1.1

### ISSUE THREAD

**Issue by vicwebdesign** [yairEO/photobox#128]
photbox.js  does not work with the latest 3.1.1 jquery script

**Comment by yairEO** [comment]
Thank you, I will investigate

**Comment by yairEO** [comment]
checked on Chrome (`Version 58.0.3029.110 (64-bit)`) , didn't get any error. what error are you seeing? which line?

**Comment by mz87** [comment]
thumbs.animate is not a function
jquery 3.2.1

**Comment by mz87** [comment]
use full version of jquery, not SLIM ;) that fixed my problem
